function [polarH_LT,polarV_LT,polarZ_LT, ...
    polarH_LB,polarV_LB,polarZ_LB, ...
    polarH_RT,polarV_RT,polarZ_RT, ...
    polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = callSample(sample)

if strcmp(sample,'sample1')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample1;
elseif strcmp(sample,'sample2')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample2;
elseif strcmp(sample,'sample3')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample3;
elseif strcmp(sample,'sample4')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample4;
elseif strcmp(sample,'sample5')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample5;
elseif strcmp(sample,'sample6')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample6;
elseif strcmp(sample,'sample7')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample7;
elseif strcmp(sample,'sample8')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample8;
elseif strcmp(sample,'sample9')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample9;
elseif strcmp(sample,'sample10')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample10;
elseif strcmp(sample,'sample11')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample11;
elseif strcmp(sample,'sample12')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample12;
elseif strcmp(sample,'sample13')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample13;
elseif strcmp(sample,'sample14')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample14;
elseif strcmp(sample,'sample15')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample15;
elseif strcmp(sample,'sample16')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample16;
elseif strcmp(sample,'sample17')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample17;
elseif strcmp(sample,'sample18')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample18;
elseif strcmp(sample,'sample19')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample19;
elseif strcmp(sample,'sample20')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample20;
elseif strcmp(sample,'sample21')
    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = sample21;
end