clear
close all
inversAxis = false;
isShow = false;
isSave = false;

for s=1:21
    close all
    sample = ['sample' num2str(s)];

    [polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, fig_SepVP] = callSample(sample);


    centerHRelative = 100;
    centerVRelative = 100;
    gridBin = 10;
    gridGab = 100/gridBin;
    path_result = '../../../Results/gridmethod/sample/';
    fileName = sample;

    [width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
        width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
        width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
        width_through_12_All,width_through_13_All,width_through_23_All] = ...
        gridLayoutLRBT([2,1], gridBin,gridGab, ...
            centerHRelative,centerVRelative, ...
            polarH_LT,polarV_LT,polarZ_LT, ...
            polarH_LB,polarV_LB,polarZ_LB, ...
            polarH_RT,polarV_RT,polarZ_RT, ...
            polarH_RB,polarV_RB,polarZ_RB, ...
            path_result, fileName, inversAxis, isShow, isSave);

 [coor_test,coor_dif_minT_m_maxF,coor_true_error, ...
    error_g1, error_g2, error_g3, ...
    true_g1, true_g2, true_g3, ...
    error_All, true_All, through_All, ...
    true_error_All, true_error_All_relative, ...
    diff_true, diff_error, ...
    min_true, max_true, min_error, max_error, ...
    sum_diff, sum_diff2, sum_diff2_relative, ...
    test_All, dif_minT_m_maxF, true_m_error_All, ...
    dif_minT_m_maxF_relative, true_m_error_All_relative ...
    ] = scoreSample( 10,...
    width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
    width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
    width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
    width_through_12_All,width_through_13_All,width_through_23_All);

    inversAxis = false
    fig_layout = plotLinePolar(polarH_LB,polarV_LB,polarZ_LB, inversAxis);
    hold on
    plot(coor_test(1), coor_test(2) , '*b')
    plot(coor_dif_minT_m_maxF(1), coor_dif_minT_m_maxF(2) , 'xr')
    plot(coor_true_error(1), coor_true_error(2) , 'og')

    hold off
    saveas(fig_layout,[path_result 'coor/' sample '.png']);
    
    scoreAll( polarH_LT,polarV_LT,polarZ_LT,polarH_LB,polarV_LB,polarZ_LB, ...
    polarH_RT,polarV_RT,polarZ_RT,polarH_RB,polarV_RB,polarZ_RB, ...
    error_g1, error_g2, error_g3, ...
    true_g1, true_g2, true_g3, ...
    error_All, true_All, through_All, ...
    true_error_All, true_error_All_relative, ...
    diff_true, diff_error, ...
    min_true, max_true, min_error, max_error, ...
    sum_diff, sum_diff2, sum_diff2_relative, ...
    test_All, dif_minT_m_maxF, true_m_error_All, ...
    dif_minT_m_maxF_relative, true_m_error_All_relative, ...
    path_result, inversAxis, sample)

    
    
end
