function [idX,idY] = gridLayout(centerHRelative, centerVRelative, ...
                    polarHRelative, polarVRelative, polarZRelative, ...
                    widthH, widthV, minH, minV, path_result, fileName)


gridBin = 50;
gridGab = 100/gridBin;

%% Line ABC
polarH = polarABC(polarHRelative);
polarV = polarABC(polarVRelative);
polarZ = polarABC(polarZRelative);

%% separate VP
[polarH_LT, polarH_LB, polarH_RT, polarH_RB] = separateLinesLRBT(polarH,[centerHRelative,centerVRelative]);
[polarV_LT, polarV_LB, polarV_RT, polarV_RB] = separateLinesLRBT(polarV,[centerHRelative,centerVRelative]);
[polarZ_LT, polarZ_LB, polarZ_RT, polarZ_RB] = separateLinesLRBT(polarZ,[centerHRelative,centerVRelative]);

fig_SepVP = plotSepVP(polarH_LT,polarV_LT,polarZ_LT, ...
    polarH_LB,polarV_LB,polarZ_LB, ...
    polarH_RT,polarV_RT,polarZ_RT, ...
    polarH_RB,polarV_RB,polarZ_RB, ...
    true);
path_sepVP = [path_result 'grid/' fileName];
if ~exist(path_sepVP, 'dir')
    mkdir(path_sepVP)
end
        
saveas(fig_SepVP,[path_sepVP '/SepVP.png']);

% path_score = [path_result 'score/' fileName ];
%     if ~exist(path_score, 'dir')
%        mkdir(path_score)
%     end
% gridLayoutLT(gridBin,gridGab, ...
%     centerHRelative,centerVRelative, ...
%     polarH_LT,polarV_LT,polarZ_LT, ...
%     polarH_LB,polarV_LB,polarZ_LB, ...
%     polarH_RT,polarV_RT,polarZ_RT, ...
%     polarH_RB,polarV_RB,polarZ_RB, ...
%     path_result);

inversAxis = true;
isShow = false;
isSave = false;
%%
% if ~(isempty(polarH_LT) && isempty(polarV_LT) && isempty(polarZ_LT))
%     [width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
%         width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
%         width_g1_Z_All,width_g2_Z_All,width_g3_Z_All] = ...
[width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
    width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
    width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
    width_through_12_All,width_through_13_All,width_through_23_All] = ...
        gridLayoutLRBT([1,1], gridBin,gridGab, ...
        centerHRelative,centerVRelative, ...
        polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, ...
        path_result, fileName, inversAxis, isShow, isSave);
    
    [coor_test_LT,coor_dif_minT_m_maxF_LT,coor_true_error_LT, ...
        error_g1_LT, error_g2_LT, error_g3_LT, ...
        true_g1_LT, true_g2_LT, true_g3_LT, ...
        error_All_LT, true_All_LT, through_All_LT, ...
        true_error_All_LT, true_error_All_relative_LT, ...
        diff_true_LT, diff_error_LT, ...
        min_true_LT, max_true_LT, min_error_LT, max_error_LT, ...
        sum_diff_LT, sum_diff2_LT, sum_diff2_relative_LT, ...
        dif_minT_m_maxF_LT, true_m_error_All_LT, ...
        test_All_LT, dif_minT_m_maxF_relative_LT, true_m_error_All_relative_LT ...
        ] = score( [1,1], gridBin, ...
        width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
        width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
        width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
        width_through_12_All,width_through_13_All,width_through_23_All);

    scoreAll( polarH_LT,polarV_LT,polarZ_LT,polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT,polarH_RB,polarV_RB,polarZ_RB, ...
        error_g1_LT, error_g2_LT, error_g3_LT, ...
        true_g1_LT, true_g2_LT, true_g3_LT, ...
        error_All_LT, true_All_LT, through_All_LT, ...
        true_error_All_LT, true_error_All_relative_LT, ...
        diff_true_LT, diff_error_LT, ...
        min_true_LT, max_true_LT, min_error_LT, max_error_LT, ...
        sum_diff_LT, sum_diff2_LT, sum_diff2_relative_LT, ...
        test_All_LT, dif_minT_m_maxF_LT, true_m_error_All_LT, ...
        dif_minT_m_maxF_relative_LT, true_m_error_All_relative_LT, ...
        path_result, inversAxis,gridBin,gridGab, [fileName '/LT']);

% end
%%
% if ~(isempty(polarH_RT) && isempty(polarV_RT) && isempty(polarZ_RT))
[width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
    width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
    width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
    width_through_12_All,width_through_13_All,width_through_23_All] = ...
        gridLayoutLRBT([1,2], gridBin,gridGab, ...
        centerHRelative,centerVRelative, ...
        polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, ...
        path_result, fileName, inversAxis, isShow, isSave);
    
    [coor_test_RT,coor_dif_minT_m_maxF_RT,coor_true_error_RT, ...
        error_g1_RT, error_g2_RT, error_g3_RT, ...
        true_g1_RT, true_g2_RT, true_g3_RT, ...
        error_All_RT, true_All_RT, through_All_RT, ...
        true_error_All_RT, true_error_All_relative_RT, ...
        diff_true_RT, diff_error_RT, ...
        min_true_RT, max_true_RT, min_error_RT, max_error_RT, ...
        sum_diff_RT, sum_diff2_RT, sum_diff2_relative_RT, ...
        dif_minT_m_maxF_RT, true_m_error_All_RT, ...
        test_All_RT, dif_minT_m_maxF_relative_RT, true_m_error_All_relative_RT ...
        ] = score( [1,2], gridBin, ...
        width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
        width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
        width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
        width_through_12_All,width_through_13_All,width_through_23_All);
scoreAll( polarH_LT,polarV_LT,polarZ_LT,polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT,polarH_RB,polarV_RB,polarZ_RB, ...
        error_g1_RT, error_g2_RT, error_g3_RT, ...
        true_g1_RT, true_g2_RT, true_g3_RT, ...
        error_All_RT, true_All_RT, through_All_RT, ...
        true_error_All_RT, true_error_All_relative_RT, ...
        diff_true_RT, diff_error_RT, ...
        min_true_RT, max_true_RT, min_error_RT, max_error_RT, ...
        sum_diff_RT, sum_diff2_RT, sum_diff2_relative_RT, ...
        test_All_RT, dif_minT_m_maxF_RT, true_m_error_All_RT, ...
        dif_minT_m_maxF_relative_RT, true_m_error_All_relative_RT, ...
        path_result, inversAxis,gridBin,gridGab, [fileName '/RT']);

% end
%%
% if ~(isempty(polarH_LB) && isempty(polarV_LB) && isempty(polarZ_LB))
[width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
    width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
    width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
    width_through_12_All,width_through_13_All,width_through_23_All] = ...
    gridLayoutLRBT([2,1], gridBin,gridGab, ...
        centerHRelative,centerVRelative, ...
        polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, ...
        path_result, fileName, inversAxis, isShow, isSave);
    [coor_test_LB,coor_dif_minT_m_maxF_LB,coor_true_error_LB, ...
        error_g1_LB, error_g2_LB, error_g3_LB, ...
        true_g1_LB, true_g2_LB, true_g3_LB, ...
        error_All_LB, true_All_LB, through_All_LB, ...
        true_error_All_LB, true_error_All_relative_LB, ...
        diff_true_LB, diff_error_LB, ...
        min_true_LB, max_true_LB, min_error_LB, max_error_LB, ...
        sum_diff_LB, sum_diff2_LB, sum_diff2_relative_LB, ...
        dif_minT_m_maxF_LB, true_m_error_All_LB, ...
        test_All_LB, dif_minT_m_maxF_relative_LB, true_m_error_All_relative_LB ...
        ] = score( [2,1], gridBin, ...
        width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
        width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
        width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
        width_through_12_All,width_through_13_All,width_through_23_All);

scoreAll( polarH_LT,polarV_LT,polarZ_LT,polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT,polarH_RB,polarV_RB,polarZ_RB, ...
        error_g1_LB, error_g2_LB, error_g3_LB, ...
        true_g1_LB, true_g2_LB, true_g3_LB, ...
        error_All_LB, true_All_LB, through_All_LB, ...
        true_error_All_LB, true_error_All_relative_LB, ...
        diff_true_LB, diff_error_LB, ...
        min_true_LB, max_true_LB, min_error_LB, max_error_LB, ...
        sum_diff_LB, sum_diff2_LB, sum_diff2_relative_LB, ...
        test_All_LB, dif_minT_m_maxF_LB, true_m_error_All_LB, ...
        dif_minT_m_maxF_relative_LB, true_m_error_All_relative_LB, ...
        path_result, inversAxis,gridBin,gridGab, [fileName '/LB']);
    
% end
%%
% if ~(isempty(polarH_RB) && isempty(polarV_RB) && isempty(polarZ_RB))
[width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
    width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
    width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
    width_through_12_All,width_through_13_All,width_through_23_All] = ...
        gridLayoutLRBT([2,2], gridBin,gridGab, ...
        centerHRelative,centerVRelative, ...
        polarH_LT,polarV_LT,polarZ_LT, ...
        polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT, ...
        polarH_RB,polarV_RB,polarZ_RB, ...
        path_result, fileName, inversAxis, isShow, isSave);
    [coor_test_RB,coor_dif_minT_m_maxF_RB,coor_true_error_RB, ...
        error_g1_RB, error_g2_RB, error_g3_RB, ...
        true_g1_RB, true_g2_RB, true_g3_RB, ...
        error_All_RB, true_All_RB, through_All_RB, ...
        true_error_All_RB, true_error_All_relative_RB, ...
        diff_true_RB, diff_error_RB, ...
        min_true_RB, max_true_RB, min_error_RB, max_error_RB, ...
        sum_diff_RB, sum_diff2_RB, sum_diff2_relative_RB, ...
        dif_minT_m_maxF_RB, true_m_error_All_RB, ...
        test_All_RB, dif_minT_m_maxF_relative_RB, true_m_error_All_relative_RB ...
        ] = score( [2,2], gridBin, ...
        width_g1_H_All,width_g2_H_All,width_g3_H_All, ...
        width_g1_V_All,width_g2_V_All,width_g3_V_All, ...
        width_g1_Z_All,width_g2_Z_All,width_g3_Z_All, ...
        width_through_12_All,width_through_13_All,width_through_23_All);
    
scoreAll( polarH_LT,polarV_LT,polarZ_LT,polarH_LB,polarV_LB,polarZ_LB, ...
        polarH_RT,polarV_RT,polarZ_RT,polarH_RB,polarV_RB,polarZ_RB, ...
        error_g1_RB, error_g2_RB, error_g3_RB, ...
        true_g1_RB, true_g2_RB, true_g3_RB, ...
        error_All_RB, true_All_RB, through_All_RB, ...
        true_error_All_RB, true_error_All_relative_RB, ...
        diff_true_RB, diff_error_RB, ...
        min_true_RB, max_true_RB, min_error_RB, max_error_RB, ...
        sum_diff_RB, sum_diff2_RB, sum_diff2_relative_RB, ...
        test_All_RB, dif_minT_m_maxF_RB, true_m_error_All_RB, ...
        dif_minT_m_maxF_relative_RB, true_m_error_All_relative_RB, ...
        path_result, inversAxis,gridBin,gridGab, [fileName '/RB']);

% end

    fig_layout1 = plotLinePolar(polarH,polarV,polarZ, inversAxis);
    hold on
        plot(coor_test_LT(2), coor_test_LT(1) , '*b','MarkerSize',10)
        plot(coor_dif_minT_m_maxF_LT(2), coor_dif_minT_m_maxF_LT(1) , 'xr','MarkerSize',10)
        plot(coor_true_error_LT(2), coor_true_error_LT(1) , 'og','MarkerSize',10)
        
        plot(coor_test_RT(2), coor_test_RT(1) , '*b','MarkerSize',10)
        plot(coor_dif_minT_m_maxF_RT(2), coor_dif_minT_m_maxF_RT(1) , 'xr','MarkerSize',10)
        plot(coor_true_error_RT(2), coor_true_error_RT(1) , 'og','MarkerSize',10)
        
        plot(coor_test_LB(2), coor_test_LB(1) , '*b','MarkerSize',10)
        plot(coor_dif_minT_m_maxF_LB(2), coor_dif_minT_m_maxF_LB(1) , 'xr','MarkerSize',10)
        plot(coor_true_error_LB(2), coor_true_error_LB(1) , 'og','MarkerSize',10)
        
        plot(coor_test_RB(2), coor_test_RB(1) , '*b','MarkerSize',10)
        plot(coor_dif_minT_m_maxF_RB(2), coor_dif_minT_m_maxF_RB(1) , 'xr','MarkerSize',10)
        plot(coor_true_error_RB(2), coor_true_error_RB(1) , 'og','MarkerSize',10)
        
    hold off
    saveas(fig_layout1,[path_result 'layout/' fileName '-1.png']);
    
    error_All_LT_relative = relativeMatrix(error_All_LT);
    error_All_LB_relative = relativeMatrix(error_All_LB);
    error_All_RT_relative = relativeMatrix(error_All_RT);
    error_All_RB_relative = relativeMatrix(error_All_RB);
    
    logic_LT = error_All_LT_relative > 5;
    logic_LB = error_All_LB_relative > 5;
    logic_RT = error_All_RT_relative > 5;
    logic_RB = error_All_RB_relative > 5;
    
    log_All = logic_LT + logic_LB + logic_RT + logic_RB;
    
    sumH = sum(log_All,1);
    sumV = sum(log_All,2);
    sumH(sumH == 0) = NaN;
    sumV(sumV == 0) = NaN;
    
    if centerHRelative > 0 && centerHRelative < 90 
        [~,idxH1] = min(sumH(1,1:floor(centerHRelative/2)));
        [~,idxH2] = min(sumH(1,ceil(centerHRelative/2):end));
        locH1 = idxH1*2;
        locH2 = (floor(centerHRelative/2) + idxH2)*2;
        locH = [locH1,locH2];
    else
        [~,idxH] = min(sumH(1,:));
        locH = idxH*2;
        
    end
    if centerVRelative > 0 && centerVRelative < 90 
        [~,idxV1] = min(sumV(1:floor(centerVRelative/2),1));
        [~,idxV2] = min(sumV(ceil(centerVRelative/2):end,1));
        locV1 = idxV1*2;
        locV2 = (floor(centerVRelative/2) + idxV2)*2;
        locV = [locV1, locV2];
    else
        [~,idxV] = min(sumV(:,1));
        locV = idxV*2;
    end
    fig_layout2 = plotLinePolar(polarH,polarV,polarZ, inversAxis);
    hold on
    for i=1:gridBin
        if isnan(sumH(i)), text(100,i*gridGab,'-');
        else, text(100,i*gridGab,num2str(sumH(i))); end
        if isnan(sumV(i)), text(i*gridGab,0,'-');
        else, text(i*gridGab,0,num2str(sumV(i))); end
    end
   
    if size(locV,2) == 2 && size(locH,2) == 2
    plot([locV(1);locV(1)],[locH(1);locH(2)],':k','LineWidth',2);
    plot([locV(2);locV(2)],[locH(1);locH(2)],':k','LineWidth',2);
    plot([locV(1);locV(2)],[locH(1);locH(1)],':k','LineWidth',2);
    plot([locV(1);locV(2)],[locH(2);locH(2)],':k','LineWidth',2);
    elseif size(locV,2) == 1
        plot([locV(1);locV(1)],[locH(1);locH(2)],':k','LineWidth',2);
        plot([locV(1);centerVRelative],[locH(1);locH(1)],':k','LineWidth',2);
        plot([locV(1);centerVRelative],[locH(2);locH(2)],':k','LineWidth',2);
    elseif size(locH,2) == 1
        plot([locV(1);locV(2)],[locH(1);locH(1)],':k','LineWidth',2);
        plot([locV(1);locV(1)],[locH(1);centerHRelative],':k','LineWidth',2);
        plot([locV(2);locV(2)],[locH(1);centerHRelative],':k','LineWidth',2);
    end
    
    saveas(fig_layout2,[path_result 'layout/' fileName '-2.png']);
%     error_All_relative = error_All_LT_relative + error_All_LB_relative + error_All_RT_relative + error_All_RB_relative;
%     true_error_All_relative = true_error_All_relative_LT + true_error_All_relative_LB + true_error_All_relative_RT + true_error_All_relative_RB;
testbug = 1;
